#eurekaserver:
# image: wuyuan-configclientapprefresh:latest
# ports:
#  - 8761:8761
# volumes:
#  - /temp:/temp
# environment:
#  - JAVA_OPTS="-Xms500m -Xmx800m"
# command: bash -c "java -jar /app.jar"

version:'2'
services:
  peer1:
    image:wuyuan-eurekaserverha
    ports:
      - "8761:8761"
    environment:
      -spring.profiles.active=peer1
  peer2:
      image:wuyuan-eurekaserverha
      ports:
        - "8762:8762"
      environment:
        -spring.profiles.active=peer2
  consumerfeignhystrix:
    image:wuyuan-consumerfeignhystrix
  product:
    image:wuyuan-product
  hystrixdashborad:
    image:wuyuan-hystrixdashborad
  gatewayzuul:
    image:wuyuan-gatewayzuul
