version: '2'
services:
  peer1:
    image: wuyuan-eurekaserverha
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=peer1
  peer2:
    image: wuyuan-eurekaserverha
    ports:
      - "8762:8762"
    environment:
      - spring.profiles.active=peer2

  product:
    image: wuyuan-product
    ports:
      - "7900:7900"
  consumerfeignhystrix:
    image: wuyuan-consumerfeignhystrix
    ports:
      - "7901:7901"
  hystrixdashborad:
    image: wuyuan-hystrixdashborad
    ports:
      - "8030:8030"
  gatewayzuul:
    image: wuyuan-gatewayzuul
    ports:
      - "8040:8040"
